apiVersion: 1

datasources:
  - name: ProductionDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: production
    user: collector
    secureJsonData:
      password: 'secure_password_here'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
